export const brand = { name: 'Enlace Operativo', tagline: 'Seguridad con criterio.', locale: 'es-MX', demo: 'E.O.S.P., S.A. de C.V. · Información corporativa 2026' } as const;
export const navigation = [{ href: '/servicios', label: 'Soluciones' }, { href: '/nosotros', label: 'Nosotros' }, { href: '/cobertura', label: 'Cobertura' }];
export const services = [
  { id: '01', slug: 'seguridad-patrimonial', title: 'Seguridad patrimonial', short: 'El control empieza en el acceso.', description: 'Personas, instalaciones y activos protegidos por un plan que entiende tu operación.', includes: ['Control de accesos y registro de visitantes', 'Rondines documentados y supervisión operativa', 'Protocolos de respuesta y reporte de incidencias'], metric: 'Rondines cada 60 min', context: '[DATO A VALIDAR] Frecuencia sujeta al diagnóstico.', category: 'PERSONAS + ESPACIOS', shape: 'perimeter', question: '¿Qué necesita tu instalación?', answer: 'El diagnóstico considera turnos, accesos, riesgos y continuidad operativa. La propuesta define el personal, los protocolos y los indicadores antes del inicio.' },
  { id: '02', slug: 'proteccion-ejecutiva', title: 'Protección ejecutiva', short: 'Discreción que te deja avanzar.', description: 'Un esquema de protección personal que se adapta a tu agenda, tus trayectos y tu nivel de exposición.', includes: ['Análisis de exposición y planeación de rutas', 'Acompañamiento y coordinación de traslados', 'Protocolos de contingencia y comunicación'], metric: 'Planeación 24 h antes', context: '[DATO A VALIDAR] Anticipación propuesta por servicio.', category: 'PROTECCIÓN PERSONAL', shape: 'orbit', question: '¿Cómo se diseña el acompañamiento?', answer: 'Partimos de una evaluación de exposición y de las actividades a proteger. El alcance se acuerda de forma confidencial, sin publicar rutas ni información sensible.' },
  { id: '03', slug: 'seguridad-corporativa', title: 'Seguridad corporativa', short: 'Tu operación, sin puntos ciegos.', description: 'Protección coordinada para oficinas, comercios y centros de trabajo con exigencias distintas.', includes: ['Análisis de vulnerabilidad por instalación', 'Procedimientos para empleados y proveedores', 'Tablero de incidencias y revisión con responsables'], metric: '1 reporte por turno', context: '[DATO A VALIDAR] Cadencia propuesta.', category: 'CONTINUIDAD OPERATIVA', shape: 'grid', question: '¿Se pueden coordinar varias sedes?', answer: 'Sí, el diseño contempla un protocolo común y ajustes por inmueble. La capacidad y cobertura de cada sede deben confirmarse antes de contratar.' },
  { id: '04', slug: 'seguridad-residencial', title: 'Seguridad residencial', short: 'La tranquilidad empieza en casa.', description: 'Control y presencia para comunidades, fraccionamientos y conjuntos habitacionales.', includes: ['Control de entradas, salidas y visitantes', 'Rondines y consignas por comunidad', 'Coordinación con administración y residentes'], metric: 'Vigilancia 24 h', context: 'Servicio descrito en el dossier 2026, p. 6. Alcance a acordar.', category: 'COMUNIDADES + RESIDENCIAS', shape: 'perimeter', question: '¿Cómo se coordina con la administración?', answer: 'Se definen responsables, autorizaciones y canales de comunicación. Cada comunidad acuerda las consignas, rondines y procedimientos de acceso.' },
  { id: '05', slug: 'seguridad-comercial', title: 'Seguridad comercial', short: 'Cuidamos el espacio que compartes.', description: 'Protección para centros comerciales y tiendas departamentales, alineada con la experiencia de tus visitantes.', includes: ['Control de accesos y presencia en piso', 'Atención y canalización de incidencias', 'Coordinación con responsables del establecimiento'], metric: '1 reporte por turno', context: '[DATO A VALIDAR] Cadencia propuesta por establecimiento.', category: 'COMERCIO + HOSPITALIDAD', shape: 'orbit', question: '¿La presencia se adapta al establecimiento?', answer: 'El uniforme, equipamiento y consignas se ajustan al entorno. El material corporativo contempla esquemas élite, pie tierra y comando.' },
  { id: '06', slug: 'tecnologia-y-monitoreo', title: 'Tecnología y monitoreo', short: 'Más visibilidad. Mejor coordinación.', description: 'Comunicación, videovigilancia y control de rondines como parte de una estructura de seguridad integrada.', includes: ['Sistemas de control y CCTV', 'Radios de frecuencia y comunicación celular', 'Puntos automatizados de rondín'], metric: '7 recursos operativos', context: 'Categorías de equipo descritas en el dossier 2026, p. 10.', category: 'CONTROL + TECNOLOGÍA', shape: 'grid', question: '¿Qué tecnología necesita mi instalación?', answer: 'El diagnóstico define cámaras, puntos de rondín y comunicaciones según los riesgos del inmueble. Los equipos y su mantenimiento se detallan en la propuesta.' },
] as const;
export type Service = (typeof services)[number];
export const contact = { phone:'55 1106 2161', phoneHref:'tel:+525511062161', secondaryPhone:'55 9130 7754', whatsapp:'55 5195 2023', whatsappHref:'https://wa.me/525551952023', email:'asis.enlaceoperativo@eosp.mx', address:'Río Volga 3 Bis, 2º piso, Col. Cuauhtémoc, CDMX, C.P. 06500', hours:'Lunes a viernes, 9:00 a 18:00 h', source:'Dossier corporativo 2026, p. 17' } as const;
export const locations = [
 {id:'CDMX',name:'Ciudad de México',state:'Ciudad de México',region:'Oficina central',lon:-99.1332,lat:19.4326,description:'Coordinación y atención comercial desde Río Volga 3 Bis, colonia Cuauhtémoc.',note:'Dirección publicada en el dossier corporativo 2026.'},
 {id:'JAL',name:'Jalisco',state:'Jalisco',region:'Occidente',lon:-103.387421,lat:20.721106,description:'Cobertura indicada para Jalisco en el material corporativo de Enlace Operativo.',note:'Disponibilidad y alcance sujetos al diagnóstico de tu ubicación.'},
 {id:'NL',name:'Nuevo León',state:'Nuevo León',region:'Norte',lon:-100.3161,lat:25.6866,description:'Cobertura y registro estatal incluidos en la carpeta comercial 2026.',note:'Solicita confirmación de disponibilidad y documentación actualizada.'},
 {id:'SLP',name:'San Luis Potosí',state:'San Luis Potosí',region:'Centro-norte',lon:-100.97135138,lat:22.15234352,description:'Presencia en San Luis Potosí declarada en el dossier corporativo 2026.',note:'Disponibilidad y alcance sujetos al diagnóstico de tu ubicación.'},
] as const;
export const coverageStates=['Estado de México','Ciudad de México','Nuevo León','San Luis Potosí','Aguascalientes','Zacatecas','Jalisco','Michoacán','Guanajuato','Querétaro','Nayarit','Morelos'];
export const promises = [
  { number: '01', title: 'Primero entendemos. Después protegemos.', text: 'Un diagnóstico de tus riesgos define el alcance, los responsables y los protocolos.' },
  { number: '02', title: 'Lo que sucede queda documentado.', text: 'Registros de rondines, incidencias y seguimiento para revisar la operación con evidencia.' },
  { number: '03', title: 'Un responsable. Una línea clara.', text: 'Canales de escalamiento acordados para saber a quién acudir y qué esperar.' },
];
export const certifications = [{name:'ISO 9001:2015',label:'Gestión de calidad'},{name:'ISO 14001:2015',label:'Gestión ambiental'},{name:'ISO 45001:2018',label:'Seguridad y salud'}];
export const testimonials = [{quote:'Necesitábamos ordenar los accesos sin frenar las entregas. El nuevo protocolo nos dio responsables claros y un registro para revisar cada incidencia.',name:'Mariana R.',role:'Directora de operaciones',company:'Empresa logística por confirmar',sector:'Logística',problem:'Control de accesos y trazabilidad',placeholder:true}];
export const faqs = [{question:'¿Por dónde empezamos?',answer:'Con una conversación sobre tu operación. Después definimos el alcance de un diagnóstico y preparamos una propuesta con responsabilidades e indicadores claros.'},{question:'¿La cobertura incluye todo México?',answer:'El dossier corporativo documenta presencia en 12 estados y registro federal. Confirmamos disponibilidad, alcance y documentación aplicable para tu ubicación antes de elaborar la propuesta.'},{question:'¿Dónde consulto los permisos y certificaciones?',answer:'Puedes consultar el dossier corporativo y la carpeta comercial de 2026 en la sección Nosotros. La documentación contiene distintas fechas de autorización y revalidación; solicita el expediente actualizado antes de contratar.'}];
export const documents = [
 {name:'Dossier corporativo 2026',description:'La visión completa: servicios, equipo y cobertura.',file:'dossier-2026.pdf',year:'2026',pages:17,featured:true},
 {name:'Carpeta comercial 2026',description:'Presentación y anexos de documentación corporativa.',file:'carpeta-comercial-2026.pdf',year:'2026',pages:27,featured:true},
 {name:'Presentación institucional 2026',description:'Resumen de capacidades y atención comercial.',file:'carpeta-institucional-2026.pdf',year:'2026',pages:9,featured:false},
 {name:'Company Profile · agosto 2025',description:'Archivo corporativo.',file:'company-profile-2025.pdf',year:'2025',pages:23,featured:false},
 {name:'Carpeta · agosto 2025',description:'Archivo corporativo.',file:'carpeta-agosto-2025.pdf',year:'2025',pages:10,featured:false},
 {name:'Carpeta · 23 de julio 2025',description:'Archivo corporativo.',file:'carpeta-23-julio-2025.pdf',year:'2025',pages:9,featured:false},
 {name:'Carpeta · julio 2025',description:'Archivo corporativo.',file:'carpeta-julio-2025.pdf',year:'2025',pages:9,featured:false},
] as const;
export const commercialLinks = [
 {name:'Grupo ampm',image:'/assets/logo-cliente-ampm.png'},
 {name:'Grupo Salinas',image:'/assets/logo-cliente-grupo-salinas.png'},
 {name:'Fresko',image:'/assets/logo-cliente-fresko.png'},
 {name:'TV Azteca',image:'/assets/logo-cliente-tv-azteca.png'},
 {name:'Las Alcobas',image:'/assets/logo-cliente-las-alcobas.png'},
 {name:'Universidad Autónoma Metropolitana',image:'/assets/logo-cliente-uam.png'},
];
export const teamCapabilities = [
 {title:'Capacitación permanente',description:'Derechos humanos, trato digno, Protección Civil y protocolos de seguridad.',source:'Dossier 2026, p. 7'},
 {title:'Una imagen para cada entorno',description:'Uniformes élite, pie tierra y comando, según las necesidades del servicio.',source:'Dossier 2026, p. 9'},
 {title:'Supervisión con presencia',description:'Unidades rotuladas para supervisión, rondines y soporte a la operación.',source:'Dossier 2026, p. 11'},
];
