'use client';
import Link from 'next/link';
import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { ArrowUpRight, Check } from 'lucide-react';
import { contactSchema, type ContactValues, formCopy } from '@/content/forms';
import { services } from '@/content/site';
export function ContactForm({ initialService = '' }: { initialService?: string }) {
 const [status,setStatus]=useState<'idle'|'success'|'error'>('idle');
 const {register,handleSubmit,formState:{errors,isSubmitting},reset}=useForm<ContactValues>({resolver:zodResolver(contactSchema),mode:'onTouched',defaultValues:{service:initialService}});
 const submit=async(values:ContactValues)=>{setStatus('idle');try{const response=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(values)});if(!response.ok)throw new Error('request');setStatus('success');reset();}catch{setStatus('error');}};
 if(status==='success')return <div className="form-success" role="status"><span className="success-symbol"><Check/></span><h2>{formCopy.success}</h2><p>{formCopy.successDetail}</p><button className="button button-secondary" onClick={()=>setStatus('idle')}>Volver al formulario<ArrowUpRight size={18}/></button></div>;
 return <form className="contact-form" onSubmit={handleSubmit(submit)} noValidate aria-label="Solicitar diagnóstico" aria-busy={isSubmitting}><div className="form-grid">{([{name:'name',label:'Nombre completo',autocomplete:'name',placeholder:'¿Cómo te llamas?',type:'text'},{name:'email',label:'Correo de trabajo',autocomplete:'email',placeholder:'nombre@empresa.com',type:'email'},{name:'company',label:'Empresa',autocomplete:'organization',placeholder:'Nombre de tu empresa',type:'text'}] as const).map(field=><div className="field" key={field.name}><label htmlFor={field.name}>{field.label} <span>*</span></label><input id={field.name} type={field.type} autoComplete={field.autocomplete} placeholder={field.placeholder} {...register(field.name)} aria-invalid={!!errors[field.name]} aria-describedby={errors[field.name]?`${field.name}-error`:undefined}/>{errors[field.name]&&<p className="field-error" id={`${field.name}-error`} role="alert">{errors[field.name]?.message}</p>}</div>)}<div className="field"><label htmlFor="service">Solución de interés <span>*</span></label><select id="service" {...register('service')} aria-invalid={!!errors.service} aria-describedby={errors.service?'service-error':undefined}><option value="">Selecciona una solución</option>{services.map(service=><option value={service.slug} key={service.slug}>{service.title}</option>)}<option value="diagnostico">Necesito orientación</option></select>{errors.service&&<p className="field-error" id="service-error" role="alert">{errors.service.message}</p>}</div></div><div className="field"><label htmlFor="message">¿Qué necesitas proteger? <span>*</span></label><textarea id="message" rows={4} placeholder="Ubicación, tipo de operación y el reto que te gustaría resolver." {...register('message')} aria-invalid={!!errors.message} aria-describedby={errors.message?'message-error':'message-help'}/><p id="message-help" className="microcopy">Evita compartir rutas, contraseñas o información sensible.</p>{errors.message&&<p className="field-error" id="message-error" role="alert">{errors.message.message}</p>}</div><div className="consent"><input type="checkbox" id="privacy" {...register('privacy')} aria-invalid={!!errors.privacy} aria-describedby={errors.privacy?'privacy-error':undefined}/><label htmlFor="privacy">He leído el <Link href="/privacidad">aviso de privacidad</Link>. *</label></div>{errors.privacy&&<p className="field-error" id="privacy-error" role="alert">{errors.privacy.message}</p>}<button className="button button-primary" type="submit" disabled={isSubmitting}><span>{isSubmitting?formCopy.sending:formCopy.submit}</span><ArrowUpRight size={18} aria-hidden="true"/></button>{status==='error'&&<p className="field-error" role="alert">{formCopy.error}</p>}<p className="microcopy form-disclaimer">{formCopy.demo}</p></form>;
}
