import Image from 'next/image';
import Link from 'next/link';
import { ArrowUpRight, FileText, ArrowDownToLine } from 'lucide-react';
import { Button, SectionHeading, Accordion } from './ui';
import { ContactForm } from './contact-form';
import { LocationMap } from './location-map';
import { Newsletter } from './newsletter';
import { promises, contact, commercialLinks, documents, faqs } from '@/content/site';
import { media } from '@/content/media';
export function MethodSection(){return <section className="section method-section"><div><SectionHeading number="02" label="NUESTRO MÉTODO">La confianza<br/>se construye<br/><span className="accent-text">en campo.</span></SectionHeading><div className="method-photo"><Image {...media['personal-industrial']} alt="Elemento de Enlace Operativo en una instalación industrial" sizes="(max-width: 700px) 100vw, 35vw" placeholder="blur"/><span className="photo-label mono">PERSONAL / ENLACE OPERATIVO</span></div></div><div className="method-copy"><p className="large-copy">No hay dos operaciones iguales.<br/>Tampoco debería haber dos planes de seguridad iguales.</p><div className="promise-list">{promises.map(promise=><article key={promise.number} data-reveal><span className="mono">{promise.number}</span><h3>{promise.title}</h3><p>{promise.text}</p></article>)}</div><Button href="/nosotros" variant="ghost">Así trabajamos</Button></div></section>}
export function CoverageSection(){return <section className="section coverage-section"><div className="section-title-row"><SectionHeading number="03" label="COBERTURA">Cerca de tu operación.<br/>Donde lo necesitas.</SectionHeading><p>12 estados documentados.<br/>Una coordinación en común.<br/><span className="microcopy">Fuente: dossier corporativo 2026.</span></p></div><LocationMap/><Button href="/cobertura" variant="ghost">Explorar la cobertura</Button></section>}
export function CredentialsSection(){return <section className="section credentials-section"><div className="credential-heading"><p className="eyebrow"><FileText size={16}/> RESPALDO DOCUMENTAL</p><h2>La confianza también<br/>se puede consultar.</h2><p>Accede al material corporativo y conoce el alcance que Enlace Operativo documenta.</p></div><div className="credentials"><article><span className="mono">REGISTRO FEDERAL DOCUMENTADO</span><h3>DGSP/193-16/3178</h3><p>Incluido en la carpeta comercial 2026.</p></article><article><span className="mono">REGISTRO REPSE DOCUMENTADO</span><h3>STPS / 2024</h3><p>Acuerdo AR142764/2024 · folio 35946.</p></article><p className="microcopy">Los anexos contienen diferentes fechas de autorización y revalidación. Solicita el expediente actualizado para confirmar su vigencia y alcance.</p><Link className="text-link" href="/documents/carpeta-comercial-2026.pdf" target="_blank">Consultar carpeta comercial <ArrowUpRight size={17}/><span className="sr-only">PDF, nueva pestaña</span></Link></div></section>}
export function CommercialLinks(){return <section className="section commercial-links"><p className="eyebrow">RELACIONES QUE FORMAN PARTE DE NUESTRA HISTORIA</p><div className="client-logos">{commercialLinks.map(client=><div key={client.name}><Image src={client.image} alt={client.name} width={150} height={80} sizes="(max-width:600px) 33vw, 15vw"/></div>)}</div><p className="microcopy">Vínculos presentes en el material corporativo 2026. La relación y el alcance actual deben confirmarse.</p></section>}
export function ContactSection(){return <section className="section contact-section" id="contacto"><div><SectionHeading number="04" label="HABLEMOS">La siguiente<br/>decisión es<br/><span className="accent-text">proteger.</span></SectionHeading><p>Cuéntanos qué necesitas cuidar.<br/>Empecemos a diseñar el plan.</p><div className="direct-contact"><a href={contact.phoneHref}>{contact.phone}<ArrowUpRight size={18}/></a><a href={contact.whatsappHref} target="_blank" rel="noopener noreferrer">Escríbenos por WhatsApp<ArrowUpRight size={18}/></a><p className="microcopy">{contact.hours}</p></div></div><ContactForm/></section>}
export function NewsSection(){return <section className="section newsletter-section"><div><p className="eyebrow">ALERTAS DE SEGURIDAD</p><h2>Anticiparte empieza<br/>por estar informado.</h2><p>Recibe una selección semanal de prevención, señales de riesgo y recomendaciones para tu operación.</p></div><Newsletter/></section>}
export function DocumentLibrary(){return <section className="section documents-section" id="documentos"><SectionHeading number="05" label="MATERIAL CORPORATIVO">Conoce los detalles.</SectionHeading><div className="document-grid">{documents.filter(doc=>doc.featured).map(doc=><a key={doc.file} className="document-card" href={'/documents/'+doc.file} target="_blank" rel="noopener noreferrer"><FileText/><span className="eyebrow">{doc.year} / PDF · {doc.pages} PÁGINAS</span><h3>{doc.name}</h3><p>{doc.description}</p><span className="text-link">Abrir documento<ArrowUpRight size={17}/></span><span className="sr-only">Se abre en otra pestaña</span></a>)}</div><details className="archive-docs"><summary>Más presentaciones y archivo corporativo <ArrowDownToLine size={18}/></summary>{documents.filter(doc=>!doc.featured).map(doc=><a key={doc.file} href={'/documents/'+doc.file} target="_blank" rel="noopener noreferrer"><span>{doc.name}</span><span className="mono">PDF / {doc.pages} PÁG.<ArrowUpRight size={15}/></span></a>)}</details><p className="microcopy">Documentos originales aportados por la empresa. Sus datos corresponden a cada edición.</p></section>}
export function FAQSection(){return <section className="section faq-section"><SectionHeading number="05" label="PREGUNTAS FRECUENTES">Antes de empezar.</SectionHeading><Accordion items={faqs}/></section>}
