import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { Check, ArrowUpRight } from 'lucide-react';
import { services } from '@/content/site';
import { media } from '@/content/media';
import { Button, Accordion, SectionHeading, ServiceCard } from '@/components/ui';
export function generateStaticParams(){return services.map(service=>({slug:service.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const{slug}=await params;const service=services.find(s=>s.slug===slug);return{title:service?.title??'Solución no encontrada',description:service?.description};}
export default async function ServicePage({params}:{params:Promise<{slug:string}>}){const{slug}=await params;const service=services.find(s=>s.slug===slug);if(!service)notFound();const index=services.findIndex(s=>s.slug===slug);const photo=index===2?media['personal-industrial']:index===4?media['equipo-tienda']:media['equipo-comercio'];return <main id="main"><section className="section page-intro service-detail-intro"><Link className="eyebrow" href="/servicios">SOLUCIONES / {service.id}</Link><h1>{service.title}<span className="accent-text">.</span></h1><p className="large-copy">{service.short}</p><Button href={'/contacto?servicio='+service.slug}>Diseñar mi plan</Button></section><section className="section service-detail"><div className="detail-image"><Image {...photo} alt="Personal de Enlace Operativo durante actividades de seguridad" sizes="(max-width:768px) 100vw, 50vw" placeholder="blur"/><span className="photo-label mono">MATERIAL CORPORATIVO / ENLACE OPERATIVO</span></div><div><SectionHeading number={service.id} label="ALCANCE">Protección que entiende<br/>tu operación.</SectionHeading><p>{service.description}</p><ul className="includes-list">{service.includes.map(item=><li key={item}><Check size={18} aria-hidden="true"/>{item}</li>)}</ul><div className="service-metric"><strong>{service.metric}</strong><p className="microcopy">{service.context}</p></div><Accordion items={[{question:service.question,answer:service.answer}]}/><Button href={'/contacto?servicio='+service.slug} variant="ghost">Hablar de esta solución</Button></div></section><section className="section related-section"><SectionHeading number="+" label="CAPACIDADES COMPLEMENTARIAS">Un perímetro conectado.</SectionHeading><div className="service-grid">{[services[(index+1)%services.length],services[(index+2)%services.length]].map(item=><ServiceCard key={item.slug} service={item}/>)}</div><Link className="text-link" href="/servicios">Todas las soluciones<ArrowUpRight size={17}/></Link></section></main>}
